
default: &default
  adapter: postgresql
  encoding: unicode
  username: admin
  password: admin
  host: localhost
  port: 5432
  

development:
  <<: *default
  database: controle_db


test:
  <<: *default
  database: controle_db

production:
  <<: *default
  database: Controle_db
  username: admin
  password: <%= ENV["TESTE_PROJECT_DATABASE_PASSWORD"] %>